### ISSUE TITLE
chrome无法使用

### ISSUE THREAD

**Issue by dapao9999** [stephenyin/jddbd#1]
chrome-extension://jdnfahmnjjpffiidendnhjnbhpmldjae/jd.js:85 上限价格:13333元
chrome-extension://jdnfahmnjjpffiidendnhjnbhpmldjae/jd.js:86 增加幅度:10元
chrome-extension://jdnfahmnjjpffiidendnhjnbhpmldjae/jd.js:87 提交时间:最后1秒
chrome-extension://jdnfahmnjjpffiidendnhjnbhpmldjae/jd.js:88 仅最后时刻提交上限价格:false
extensions::uncaught_exception_handler:8 Error in event handler for extension.onRequest: TypeError: Cannot read property 'children' of null
    at chrome-extension://jdnfahmnjjpffiidendnhjnbhpmldjae/jd.js:91:53handler @ extensions::uncaught_exception_handler:8

是姿势不正确吗。。。

**Comment by stephenyin** [comment]
前段时间jd夺宝岛页面改版了，代码还没更新呢，暂时用不了。见笑了

**Comment by dapao9999** [comment]
原来如此,,明白了,,,,,
